# Generated by Django 6.0.3 on 2026-04-03 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_delete_departmentapprovalconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=30, unique=True)),
                ('project_name', models.CharField(max_length=150)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('owning_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to='accounts.department')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'PS_A8_PROJ',
                'ordering': ['project_code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('ADJUST', 'Adjust')], max_length=20)),
                ('source_type', models.CharField(choices=[('PURCHASE', 'Purchase Request'), ('TRAVEL', 'Travel Request')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_budget_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_entries', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Budget Entry',
                'verbose_name_plural': 'Project Budget Entries',
                'db_table': 'PS_A8_PROJ_BUD',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
