# Generated by Django 6.0.3 on 2026-05-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_budget_approval_and_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudgetentry',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='projectbudgetentry',
            name='source_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='projectbudgetentry',
            name='source_exchange_rate_source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='projectbudgetentry',
            name='source_transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectbudgetentry',
            name='source_transaction_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='', max_length=10),
        ),
    ]
