# Generated by Django 6.0.3 on 2026-05-12 22:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_departmentapprovalconfig'),
        ('projects', '0006_projectbudgetentry_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGeneralProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField()),
                ('budget_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_department_general_project_setups', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_project_setups', to='accounts.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_general_setups', to='projects.project')),
            ],
            options={
                'verbose_name': 'Department General Project',
                'verbose_name_plural': 'Department General Projects',
                'db_table': 'PS_A8_DEPT_GEN_PROJ',
                'ordering': ['-fiscal_year', 'department__dept_code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('department', 'fiscal_year'), name='uq_active_dept_general_project_year')],
            },
        ),
    ]
