# Generated by Django 6.0.3 on 2026-05-12 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_departmentgeneralproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_adjustments', to=settings.AUTH_USER_MODEL)),
                ('posted_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_request', to='projects.projectbudgetentry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_adjustment_requests', to='projects.project')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_budget_adjustments', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_budget_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Adjustment Request',
                'verbose_name_plural': 'Budget Adjustment Requests',
                'db_table': 'PS_A8_PROJ_BUD_ADJ_REQ',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
    ]
