# Generated by Django 6.0.3 on 2026-04-10 00:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_delete_departmentapprovalconfig'),
        ('approvals', '0008_backfill_generic_request_refs'),
        ('projects', '0002_alter_projectbudgetentry_entry_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequestNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Travel Request Number Sequence',
                'verbose_name_plural': 'Travel Request Number Sequences',
                'db_table': 'PS_A8_TR_SEQ',
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('IN_TRIP', 'In Trip'), ('EXPENSE_PENDING', 'Expense Pending'), ('EXPENSE_SUBMITTED', 'Expense Submitted'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('purpose', models.CharField(max_length=200)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_requests', to='approvals.approvalrule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='projects.project')),
                ('request_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='accounts.department')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Request',
                'verbose_name_plural': 'Travel Requests',
                'db_table': 'PS_A8_TR_HDR',
                'ordering': ['-request_date', 'travel_no'],
            },
        ),
        migrations.CreateModel(
            name='TravelItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('trip_date', models.DateField()),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('transport_type', models.CharField(choices=[('AIR', 'Air'), ('TRAIN', 'Train'), ('TAXI', 'Taxi'), ('CAR_RENTAL', 'Car Rental'), ('BUS', 'Bus'), ('PRIVATE_CAR', 'Private Car'), ('OTHER', 'Other')], default='AIR', max_length=30)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='travel.travelrequest')),
            ],
            options={
                'verbose_name': 'Travel Itinerary',
                'verbose_name_plural': 'Travel Itineraries',
                'db_table': 'PS_A8_TR_ITN',
                'ordering': ['travel_request', 'line_no'],
                'unique_together': {('travel_request', 'line_no')},
            },
        ),
        migrations.CreateModel(
            name='TravelEstimatedExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('expense_type', models.CharField(choices=[('AIRFARE', 'Airfare'), ('TRAIN', 'Train'), ('TAXI', 'Taxi'), ('HOTEL', 'Hotel'), ('MEAL', 'Meal'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('VISA', 'Visa'), ('REGISTRATION', 'Registration'), ('MISC', 'Misc')], max_length=30)),
                ('location_mode', models.CharField(choices=[('TRANSIT', 'Transit'), ('STAY', 'Stay'), ('LOCAL', 'Local')], max_length=20)),
                ('expense_date', models.DateField()),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('from_location', models.CharField(blank=True, default='', max_length=100)),
                ('to_location', models.CharField(blank=True, default='', max_length=100)),
                ('departure_dt', models.DateTimeField(blank=True, null=True)),
                ('arrival_dt', models.DateTimeField(blank=True, null=True)),
                ('expense_location', models.CharField(blank=True, default='', max_length=100)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(default=0)),
                ('policy_limit_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('over_limit_flag', models.BooleanField(default=False)),
                ('receipt_required_flag', models.BooleanField(default=False)),
                ('receipt_attached_flag', models.BooleanField(default=False)),
                ('exception_reason', models.CharField(blank=True, default='', max_length=300)),
                ('itinerary_line_no', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimated_expense_lines', to='travel.travelrequest')),
            ],
            options={
                'verbose_name': 'Travel Estimated Expense Line',
                'verbose_name_plural': 'Travel Estimated Expense Lines',
                'db_table': 'PS_A8_TR_EST_LN',
                'ordering': ['travel_request', 'line_no'],
                'unique_together': {('travel_request', 'line_no')},
            },
        ),
    ]
