# Generated by Django 6.0.3 on 2026-04-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelestimatedexpenseline',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='travelestimatedexpenseline',
            name='expense_type',
            field=models.CharField(choices=[('AIRFARE', 'Airfare'), ('TRAIN', 'Train'), ('TAXI', 'Taxi'), ('CAR_RENTAL', 'Car Rental'), ('BUS', 'Bus'), ('HOTEL', 'Hotel'), ('MEAL', 'Meal'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('VISA', 'Visa'), ('REGISTRATION', 'Registration'), ('MISC', 'Misc')], max_length=30),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
    ]
