# Generated by Django 6.0.3 on 2026-04-10 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_travelestimatedexpenseline_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelitinerary',
            name='transport_type',
            field=models.CharField(choices=[('AIR', 'Air'), ('TRAIN', 'Train'), ('TAXI', 'Taxi'), ('CAR_RENTAL', 'Car Rental'), ('BUS', 'Bus'), ('PRIVATE_CAR', 'Private Car'), ('CORPORATE_CAR', 'Corporate Car'), ('OTHER', 'Other')], default='AIR', max_length=30),
        ),
        migrations.CreateModel(
            name='TravelRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled'), ('TASK_APPROVED', 'Task Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], max_length=30)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(blank=True, default='', max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acting_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_request_history_entries', to=settings.AUTH_USER_MODEL)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='travel.travelrequest')),
            ],
            options={
                'verbose_name': 'Travel Request History',
                'verbose_name_plural': 'Travel Request Histories',
                'db_table': 'PS_A8_TR_HIS',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
