# Generated by Django 6.0.3 on 2026-04-10 23:28

import django.db.models.deletion
import travel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_travelitinerary_transport_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ITINERARY', 'Itinerary'), ('BOOKING', 'Booking Confirmation'), ('HOTEL', 'Hotel Document'), ('INVITATION', 'Invitation'), ('VISA', 'Visa Support'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(upload_to=travel.models.travel_attachment_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='travel.travelrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_request_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Request Attachment',
                'verbose_name_plural': 'Travel Request Attachments',
                'db_table': 'PS_A8_TR_ATT',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
