# Generated by Django 6.0.3 on 2026-04-13 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_travelrequestattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequestContentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('HEADER_CREATED', 'Header Created'), ('HEADER_UPDATED', 'Header Updated'), ('ITINERARY_ADDED', 'Itinerary Added'), ('ITINERARY_UPDATED', 'Itinerary Updated'), ('ITINERARY_DELETED', 'Itinerary Deleted'), ('EXPENSE_ADDED', 'Expense Added'), ('EXPENSE_UPDATED', 'Expense Updated'), ('EXPENSE_DELETED', 'Expense Deleted')], max_length=30)),
                ('section', models.CharField(blank=True, default='', max_length=30)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('line_no', models.IntegerField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_request_content_audits', to=settings.AUTH_USER_MODEL)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_audits', to='travel.travelrequest')),
            ],
            options={
                'verbose_name': 'Travel Request Content Audit',
                'verbose_name_plural': 'Travel Request Content Audits',
                'db_table': 'PS_A8_TR_AUD',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
