# Generated by Django 6.0.3 on 2026-04-13 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_travelrequestcontentaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='actual_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='TravelActualExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('expense_type', models.CharField(choices=[('AIRFARE', 'Airfare'), ('TRAIN', 'Train'), ('TAXI', 'Taxi'), ('CAR_RENTAL', 'Car Rental'), ('BUS', 'Bus'), ('HOTEL', 'Hotel'), ('MEAL', 'Meal'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('VISA', 'Visa'), ('REGISTRATION', 'Registration'), ('MISC', 'Misc')], max_length=30)),
                ('expense_date', models.DateField()),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=100)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('expense_location', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_actual_expense_lines', to=settings.AUTH_USER_MODEL)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_expense_lines', to='travel.travelrequest')),
            ],
            options={
                'verbose_name': 'Travel Actual Expense Line',
                'verbose_name_plural': 'Travel Actual Expense Lines',
                'db_table': 'PS_A8_TR_ACT_LN',
                'ordering': ['travel_request', 'line_no'],
                'unique_together': {('travel_request', 'line_no')},
            },
        ),
    ]
