# Generated by Django 6.0.3 on 2026-04-13 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_alter_purchaserequestattachment_document_type'),
        ('travel', '0006_travelrequest_actual_total_travelactualexpenseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='estimated_expense_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_links', to='travel.travelestimatedexpenseline'),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='purchase_request_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_actual_links', to='purchase.purchaserequestline'),
        ),
        migrations.AlterField(
            model_name='travelrequesthistory',
            name='action_type',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled'), ('TASK_APPROVED', 'Task Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('ACTUAL_EXPENSE_RECORDED', 'Actual Expense Recorded')], max_length=30),
        ),
    ]
