# Generated by Django 6.0.3 on 2026-04-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_travelactualexpenseline_estimated_expense_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequesthistory',
            name='action_type',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled'), ('TASK_APPROVED', 'Task Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('ACTUAL_EXPENSE_RECORDED', 'Actual Expense Recorded'), ('CLOSED', 'Closed')], max_length=30),
        ),
    ]
