# Generated by Django 6.0.3 on 2026-05-07 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_travelrequesthistory_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='actual_review_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='actual_review_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED_TO_PROCEED', 'Approved to Proceed'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=30),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='actual_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='actual_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_actual_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='is_over_estimate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travelrequestattachment',
            name='document_type',
            field=models.CharField(choices=[('ITINERARY', 'Itinerary'), ('BOOKING', 'Booking Confirmation'), ('HOTEL', 'Hotel Document'), ('INVITATION', 'Invitation'), ('VISA', 'Visa Support'), ('OTHER', 'Other'), ('ACCOUNTING_APPROVAL', 'Accounting Approval Document')], default='OTHER', max_length=20),
        ),
    ]
