# Generated by Django 6.0.3 on 2026-05-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_per_diem_overage_and_supplemental'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='base_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='exchange_rate_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='exchange_rate_source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='transaction_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='variance_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='travelestimatedexpenseline',
            name='estimate_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='travelestimatedexpenseline',
            name='estimate_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelestimatedexpenseline',
            name='estimated_base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelestimatedexpenseline',
            name='estimated_base_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='travelestimatedexpenseline',
            name='estimated_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='travelestimatedexpenseline',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelestimatedexpenseline',
            name='exchange_rate_source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='per_diem_base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='per_diem_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='per_diem_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='per_diem_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
