# Generated by Django 6.0.3 on 2026-05-12 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_travelactualexpenseline_base_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='entry_type',
            field=models.CharField(choices=[('ACTUAL_SPEND', 'Actual Spend'), ('REFUND', 'Refund'), ('CREDIT_MEMO', 'Credit Memo'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], default='ACTUAL_SPEND', max_length=30),
        ),
        migrations.AddField(
            model_name='travelactualexpenseline',
            name='original_actual_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_entries', to='travel.travelactualexpenseline'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='correction_reference',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='correction_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='reclosed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='reclosed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclosed_travel_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='reopen_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_travel_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelrequesthistory',
            name='action_type',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled'), ('TASK_APPROVED', 'Task Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('ACTUAL_EXPENSE_RECORDED', 'Actual Expense Recorded'), ('REOPENED', 'Reopened For Correction'), ('CLOSED', 'Closed')], max_length=30),
        ),
    ]
