# Generated by Django 6.0.3 on 2026-05-12 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_travelactualexpenseline_entry_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequestattachment',
            name='delete_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='travelrequestattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequestattachment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_travel_request_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequestattachment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
