# Generated by Django 6.0.3 on 2026-05-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_departmentapprovalconfig'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(max_length=30, unique=True)),
                ('policy_name', models.CharField(max_length=120)),
                ('request_type', models.CharField(choices=[('ALL', 'All'), ('PURCHASE', 'Purchase Request'), ('TRAVEL', 'Travel Request')], default='ALL', max_length=20)),
                ('project_type', models.CharField(blank=True, choices=[('INTERNAL', 'Internal Project'), ('TRADE_SHOW', 'Trade Show'), ('DEPARTMENT_GENERAL', 'Department General Budget'), ('CUSTOMER_SERVICE', 'Customer Service'), ('SALES_ORDER', 'Sales Order')], default='', max_length=30)),
                ('expense_type', models.CharField(blank=True, default='', max_length=30)),
                ('payment_method', models.CharField(choices=[('ALL', 'All'), ('REIMBURSEMENT', 'Reimbursement'), ('COMPANY_CARD', 'Company Card'), ('AP_INVOICE', 'AP Invoice'), ('MANUAL', 'Manual Accounting Entry')], default='ALL', max_length=30)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='', max_length=10)),
                ('amount_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requires_receipt', models.BooleanField(default=True)),
                ('requires_invoice', models.BooleanField(default=False)),
                ('allows_exception', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_policies', to='accounts.department')),
            ],
            options={
                'verbose_name': 'Receipt Policy',
                'verbose_name_plural': 'Receipt Policies',
                'db_table': 'PS_A8_FIN_RCPT_POL',
                'ordering': ['priority', 'policy_code'],
            },
        ),
    ]
