# Generated by Django 6.0.3 on 2026-05-11 21:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_receiptpolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'PS_A8_FIN_CUR',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FXVariancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(max_length=30, unique=True)),
                ('policy_name', models.CharField(max_length=120)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='', max_length=10)),
                ('fx_variance_amount_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fx_variance_amount_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fx_variance_percent_from', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('fx_variance_percent_to', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('action', models.CharField(choices=[('ALLOW', 'Allow'), ('WARNING', 'Warning'), ('REVIEW', 'Review'), ('FINANCE_REVIEW_REQUIRED', 'Finance Review Required'), ('BLOCK', 'Block')], default='REVIEW', max_length=30)),
                ('requires_comment', models.BooleanField(default=False)),
                ('requires_finance_review', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FX Variance Policy',
                'verbose_name_plural': 'FX Variance Policies',
                'db_table': 'PS_A8_FIN_FX_POL',
                'ordering': ['priority', 'policy_code'],
            },
        ),
        migrations.AddField(
            model_name='accountingreviewitem',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='accountingreviewitem',
            name='base_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='accountingreviewitem',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='accountingreviewitem',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingreviewitem',
            name='exchange_rate_source',
            field=models.CharField(blank=True, choices=[('COMPANY_RATE', 'Company Rate'), ('CARD_STATEMENT', 'Card Statement'), ('EMPLOYEE_CARD_STATEMENT', 'Employee Card Statement'), ('ACCOUNTING_OVERRIDE', 'Accounting Override'), ('MANUAL', 'Manual')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='accountingreviewitem',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='accountingreviewitem',
            name='transaction_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='accountingreviewitem',
            name='variance_type',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('FX_VARIANCE', 'FX Variance'), ('SPENDING_OVERRUN', 'Spending Overrun'), ('MIXED_VARIANCE', 'Mixed Variance'), ('BASE_CURRENCY_VARIANCE', 'Base Currency Variance'), ('NEEDS_REVIEW', 'Needs Review')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='base_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='exchange_rate_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='exchange_rate_source',
            field=models.CharField(blank=True, choices=[('COMPANY_RATE', 'Company Rate'), ('CARD_STATEMENT', 'Card Statement'), ('EMPLOYEE_CARD_STATEMENT', 'Employee Card Statement'), ('ACCOUNTING_OVERRIDE', 'Accounting Override'), ('MANUAL', 'Manual')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='transaction_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountingreviewitem',
            name='reason',
            field=models.CharField(choices=[('OVER_BUDGET', 'Over Budget'), ('FX_VARIANCE', 'FX Variance'), ('BASE_CURRENCY_VARIANCE', 'Base Currency Variance'), ('MISSING_RECEIPT', 'Missing Receipt'), ('UNMATCHED_CARD', 'Unmatched Card Transaction'), ('DUPLICATE_CARD', 'Duplicate Card Transaction'), ('POLICY_EXCEPTION', 'Policy Exception'), ('MANUAL_FLAG', 'Manual Flag')], max_length=30),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(default='USD', max_length=10)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('effective_date', models.DateField()),
                ('source', models.CharField(choices=[('COMPANY_RATE', 'Company Rate'), ('CARD_STATEMENT', 'Card Statement'), ('EMPLOYEE_CARD_STATEMENT', 'Employee Card Statement'), ('ACCOUNTING_OVERRIDE', 'Accounting Override'), ('MANUAL', 'Manual')], default='COMPANY_RATE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exchange_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'PS_A8_FIN_FX_RATE',
                'ordering': ['-effective_date', 'from_currency', 'to_currency'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'effective_date', 'source'], name='PS_A8_FIN_F_from_cu_f84402_idx')],
            },
        ),
    ]
