# Generated by Django 6.0.3 on 2026-05-12 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_departmentapprovalconfig'),
        ('finance', '0003_currency_fxvariancepolicy_and_more'),
        ('projects', '0006_projectbudgetentry_currency_and_more'),
        ('purchase', '0018_purchaseactualspend_entry_type_and_more'),
        ('travel', '0012_travelactualexpenseline_entry_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtransactionallocation',
            name='direct_project_cost_action',
            field=models.CharField(blank=True, choices=[('ALLOW', 'Allow'), ('REVIEW', 'Review'), ('REQUIRE_PROJECT_OWNER_APPROVAL', 'Require Project Owner Approval'), ('BLOCK', 'Block')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='cardtransactionallocation',
            name='project_owner_review_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='accountingreviewitem',
            name='reason',
            field=models.CharField(choices=[('OVER_BUDGET', 'Over Budget'), ('FX_VARIANCE', 'FX Variance'), ('BASE_CURRENCY_VARIANCE', 'Base Currency Variance'), ('MISSING_RECEIPT', 'Missing Receipt'), ('UNMATCHED_CARD', 'Unmatched Card Transaction'), ('DUPLICATE_CARD', 'Duplicate Card Transaction'), ('DIRECT_PROJECT_COST', 'Direct Project Cost'), ('POLICY_EXCEPTION', 'Policy Exception'), ('MANUAL_FLAG', 'Manual Flag')], max_length=30),
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_accounting_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Period',
                'verbose_name_plural': 'Accounting Periods',
                'db_table': 'PS_A8_FIN_PERIOD',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActualExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice'), ('QUOTE', 'Quote'), ('OTHER', 'Other')], default='RECEIPT', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_actual_spend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_attachments', to='purchase.purchaseactualspend')),
                ('purchase_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_expense_links', to='purchase.purchaserequestattachment')),
                ('travel_actual_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_attachments', to='travel.travelactualexpenseline')),
                ('travel_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_expense_links', to='travel.travelrequestattachment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expense_attachment_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actual Expense Attachment',
                'verbose_name_plural': 'Actual Expense Attachments',
                'db_table': 'PS_A8_FIN_ACT_ATT',
            },
        ),
        migrations.CreateModel(
            name='CardAllocationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice'), ('QUOTE', 'Quote'), ('OTHER', 'Other')], default='RECEIPT', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.cardtransactionallocation')),
                ('card_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_attachments', to='finance.cardtransaction')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_allocation_attachment_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Allocation Attachment',
                'verbose_name_plural': 'Card Allocation Attachments',
                'db_table': 'PS_A8_FIN_CARD_ATT',
            },
        ),
        migrations.CreateModel(
            name='DirectProjectCostPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(max_length=30, unique=True)),
                ('policy_name', models.CharField(max_length=120)),
                ('project_type', models.CharField(blank=True, choices=[('INTERNAL', 'Internal Project'), ('TRADE_SHOW', 'Trade Show'), ('DEPARTMENT_GENERAL', 'Department General Budget'), ('CUSTOMER_SERVICE', 'Customer Service'), ('SALES_ORDER', 'Sales Order')], default='', max_length=30)),
                ('payment_method', models.CharField(choices=[('ALL', 'All'), ('REIMBURSEMENT', 'Reimbursement'), ('COMPANY_CARD', 'Company Card'), ('AP_INVOICE', 'AP Invoice'), ('MANUAL', 'Manual Accounting Entry')], default='COMPANY_CARD', max_length=30)),
                ('amount_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('JPY', 'JPY')], default='', max_length=10)),
                ('action', models.CharField(choices=[('ALLOW', 'Allow'), ('REVIEW', 'Review'), ('REQUIRE_PROJECT_OWNER_APPROVAL', 'Require Project Owner Approval'), ('BLOCK', 'Block')], default='REVIEW', max_length=40)),
                ('requires_receipt', models.BooleanField(default=True)),
                ('requires_project_owner_review', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_project_cost_policies', to='accounts.department')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_cost_policies', to='projects.project')),
            ],
            options={
                'verbose_name': 'Direct Project Cost Policy',
                'verbose_name_plural': 'Direct Project Cost Policies',
                'db_table': 'PS_A8_FIN_DPC_POL',
                'ordering': ['priority', 'policy_code'],
            },
        ),
        migrations.AddField(
            model_name='accountingreviewitem',
            name='direct_project_cost_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_items', to='finance.directprojectcostpolicy'),
        ),
        migrations.AddField(
            model_name='cardtransactionallocation',
            name='direct_project_cost_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_allocations', to='finance.directprojectcostpolicy'),
        ),
    ]
