# Generated by Django 6.0.3 on 2026-05-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cardtransactionallocation_direct_project_cost_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingreviewitem',
            name='policy_action',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
