# Generated by Django 6.0.3 on 2026-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_accountingreviewitem_policy_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingreviewitem',
            name='reason',
            field=models.CharField(choices=[('OVER_BUDGET', 'Over Budget'), ('FX_VARIANCE', 'FX Variance'), ('BASE_CURRENCY_VARIANCE', 'Base Currency Variance'), ('MISSING_RECEIPT', 'Missing Receipt'), ('UNMATCHED_CARD', 'Unmatched Card Transaction'), ('DUPLICATE_CARD', 'Duplicate Card Transaction'), ('DUPLICATE_EXPENSE', 'Duplicate Actual Expense / Invoice'), ('DIRECT_PROJECT_COST', 'Direct Project Cost'), ('POLICY_EXCEPTION', 'Policy Exception'), ('MANUAL_FLAG', 'Manual Flag')], max_length=30),
        ),
    ]
