# Generated by Django 6.0.3 on 2026-04-03 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_delete_departmentapprovalconfig'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_no', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('request_date', models.DateField()),
                ('needed_by_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('justification', models.TextField(blank=True, default='')),
                ('vendor_suggestion', models.CharField(blank=True, default='', max_length=100)),
                ('delivery_location', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='projects.project')),
                ('request_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='accounts.department')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'db_table': 'PS_A8_PR_HDR',
                'ordering': ['-request_date', 'pr_no'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('uom', models.CharField(default='EA', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.purchaserequest')),
            ],
            options={
                'verbose_name': 'Purchase Request Line',
                'verbose_name_plural': 'Purchase Request Lines',
                'db_table': 'PS_A8_PR_LN',
                'ordering': ['request', 'line_no'],
                'unique_together': {('request', 'line_no')},
            },
        ),
    ]
