# Generated by Django 6.0.3 on 2026-04-03 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_approvalrule_specific_requester_and_more'),
        ('purchase', '0002_purchaserequesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='matched_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='approvals.approvalrule'),
        ),
    ]
