# Generated by Django 6.0.3 on 2026-04-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaserequest_matched_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequesthistory',
            name='action_type',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
