# Generated by Django 6.0.3 on 2026-04-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchaserequesthistory_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequesthistory',
            name='action_type',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TASK_CLAIMED', 'Task Claimed'), ('TASK_RELEASED_TO_POOL', 'Task Released to Pool'), ('TASK_APPROVED', 'Task Approved'), ('TASK_REJECTED', 'Task Rejected')], max_length=30),
        ),
    ]
