# Generated by Django 6.0.3 on 2026-04-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchaserequesthistory_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestline',
            name='uom',
            field=models.CharField(choices=[('EA', 'Each'), ('SET', 'Set'), ('BOX', 'Box'), ('PACK', 'Pack'), ('PAIR', 'Pair'), ('LOT', 'Lot'), ('KG', 'Kilogram'), ('LB', 'Pound'), ('M', 'Meter'), ('FT', 'Foot'), ('HOUR', 'Hour'), ('DAY', 'Day'), ('MONTH', 'Month'), ('OTHER', 'Other')], default='EA', max_length=20),
        ),
    ]
