# Generated by Django 6.0.3 on 2026-04-08 21:05

import django.db.models.deletion
import purchase.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_purchaserequestline_uom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('QUOTE', 'Vendor Quote'), ('SUPPORT', 'Supporting Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(upload_to=purchase.models.purchase_attachment_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.purchaserequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Request Attachment',
                'verbose_name_plural': 'Purchase Request Attachments',
                'db_table': 'PS_A8_PR_ATT',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
