# Generated by Django 6.0.3 on 2026-04-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_purchaserequestattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Purchase Request Number Sequence',
                'verbose_name_plural': 'Purchase Request Number Sequences',
                'db_table': 'PS_A8_PR_SEQ',
            },
        ),
    ]
