# Generated by Django 6.0.3 on 2026-04-10 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_purchaserequestcontentaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='fulfillment_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PARTIAL', 'Partially Spent'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseActualSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=100)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_actual_spend_entries', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_spend_entries', to='purchase.purchaserequest')),
            ],
            options={
                'verbose_name': 'Purchase Actual Spend',
                'verbose_name_plural': 'Purchase Actual Spend Entries',
                'db_table': 'PS_A8_PR_ACT',
                'ordering': ['-spend_date', '-id'],
            },
        ),
    ]
