# Generated by Django 6.0.3 on 2026-04-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_purchaserequest_fulfillment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestattachment',
            name='document_type',
            field=models.CharField(choices=[('QUOTE', 'Vendor Quote'), ('SUPPORT', 'Supporting Document'), ('OTHER', 'Other'), ('SPEND_RECORDED', 'Actual Spend Recorded'), ('CLOSED', 'Closed')], default='OTHER', max_length=20),
        ),
    ]
