# Generated by Django 6.0.3 on 2026-04-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_alter_purchaseactualspend_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestattachment',
            name='document_type',
            field=models.CharField(choices=[('QUOTE', 'Vendor Quote'), ('SUPPORT', 'Supporting Document'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
