# Generated by Django 6.0.3 on 2026-05-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_purchaserequestattachment_delete_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestattachment',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
