# Generated by Django 6.0.3 on 2026-04-02 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.CharField(max_length=30, unique=True)),
                ('dept_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'PS_A8_DEPT',
                'ordering': ['dept_code'],
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_approver',
            new_name='can_approve_all_departments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dept_code',
        ),
        migrations.AddField(
            model_name='user',
            name='primary_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='accounts.department'),
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_job_title', models.CharField(blank=True, default='', max_length=100)),
                ('can_approve', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='accounts.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Department',
                'verbose_name_plural': 'User Departments',
                'db_table': 'PS_A8_USR_DEPT',
                'ordering': ['user', 'department'],
                'unique_together': {('user', 'department')},
            },
        ),
    ]
