# Generated by Django 6.0.3 on 2026-04-02 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_options_department_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='dept_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('IT', 'IT'), ('FIN', 'Finance'), ('HR', 'HR'), ('PUR', 'Purchasing'), ('OPS', 'Operations'), ('EXEC', 'Executive')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_level',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('VP', 'VP'), ('C_LEVEL', 'C-Level')], default='STAFF', max_length=20),
        ),
        migrations.CreateModel(
            name='DepartmentApprovalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('PURCHASE', 'Purchase Request'), ('TRAVEL', 'Travel Request')], max_length=20)),
                ('finance_required', models.BooleanField(default=False)),
                ('purchasing_required', models.BooleanField(default=False)),
                ('hr_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('backup_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_approval_configs', to=settings.AUTH_USER_MODEL)),
                ('default_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_approval_configs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_configs', to='accounts.department')),
            ],
            options={
                'verbose_name': 'Department Approval Config',
                'verbose_name_plural': 'Department Approval Configs',
                'db_table': 'PS_A8_DEPT_APPR',
                'ordering': ['department', 'request_type'],
                'unique_together': {('department', 'request_type')},
            },
        ),
    ]
