# Generated by Django 6.0.3 on 2026-04-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_cost_center_department_dept_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentApprovalConfig',
        ),
    ]
