# Generated by Django 6.0.3 on 2026-04-02 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_department_cost_center_department_dept_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=30, unique=True)),
                ('rule_name', models.CharField(max_length=100)),
                ('request_type', models.CharField(choices=[('PURCHASE', 'Purchase Request'), ('TRAVEL', 'Travel Request')], max_length=20)),
                ('amount_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requester_level', models.CharField(blank=True, choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('VP', 'VP'), ('C_LEVEL', 'C-Level')], default='', max_length=20)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='accounts.department')),
                ('specific_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_approval_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Rule',
                'verbose_name_plural': 'Approval Rules',
                'db_table': 'PS_A8_AP_RULE',
                'ordering': ['priority', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRuleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('approver_type', models.CharField(choices=[('REQUESTER_MANAGER', 'Requester Manager'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('SPECIFIC_USER', 'Specific User'), ('DEPARTMENT_APPROVER', 'Department Approver'), ('FINANCE', 'Finance'), ('PURCHASING', 'Purchasing'), ('HR', 'HR'), ('GLOBAL_APPROVER', 'Global Approver')], max_length=30)),
                ('approver_level', models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('VP', 'VP'), ('C_LEVEL', 'C-Level')], default='', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('allow_self_skip', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approver_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rule_steps_as_department', to='accounts.department')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rule_steps_as_user', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalrule')),
            ],
            options={
                'verbose_name': 'Approval Rule Step',
                'verbose_name_plural': 'Approval Rule Steps',
                'db_table': 'PS_A8_AP_STEP',
                'ordering': ['rule', 'step_no'],
                'unique_together': {('rule', 'step_no')},
            },
        ),
    ]
