# Generated by Django 6.0.3 on 2026-04-03 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='specific_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_approval_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalrulestep',
            name='approver_level',
            field=models.CharField(blank=True, choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('VP', 'VP'), ('C_LEVEL', 'C-Level')], default='', max_length=20),
        ),
    ]
