# Generated by Django 6.0.3 on 2026-04-03 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_approvalrule_specific_requester_and_more'),
        ('purchase', '0003_purchaserequest_matched_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='purchase.purchaserequest')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='approvals.approvalrule')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='approvals.approvalrulestep')),
            ],
            options={
                'verbose_name': 'Approval Task',
                'verbose_name_plural': 'Approval Tasks',
                'db_table': 'PS_A8_AP_TASK',
                'ordering': ['purchase_request', 'step_no'],
                'unique_together': {('purchase_request', 'step_no')},
            },
        ),
    ]
