# Generated by Django 6.0.3 on 2026-04-03 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approvaltask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltask',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('POOL', 'Pool'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovalTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('CLAIMED', 'Claimed'), ('RELEASED_TO_POOL', 'Released to Pool'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('POOL', 'Pool'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('POOL', 'Pool'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], max_length=20, null=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_task_history_actions', to=settings.AUTH_USER_MODEL)),
                ('from_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_task_history_from_assignee', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='approvals.approvaltask')),
                ('to_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_task_history_to_assignee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Task History',
                'verbose_name_plural': 'Approval Task Histories',
                'db_table': 'PS_A8_AP_TSK_HIST',
                'ordering': ['-action_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTaskCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='approvals.approvaltask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_task_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Task Candidate',
                'verbose_name_plural': 'Approval Task Candidates',
                'db_table': 'PS_A8_AP_TSK_CAND',
                'ordering': ['task', 'user'],
                'unique_together': {('task', 'user')},
            },
        ),
    ]
