# Generated by Django 6.0.3 on 2026-04-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_alter_approvaltask_status_approvaltaskhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltaskhistory',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACTIVATED', 'Activated'), ('CLAIMED', 'Claimed'), ('RELEASED_TO_POOL', 'Released to Pool'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=30),
        ),
    ]
