# Generated by Django 6.0.3 on 2026-04-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_alter_approvaltaskhistory_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltask',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('POOL', 'Pool'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvaltaskhistory',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACTIVATED', 'Activated'), ('CLAIMED', 'Claimed'), ('RELEASED_TO_POOL', 'Released to Pool'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='approvaltaskhistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('POOL', 'Pool'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='approvaltaskhistory',
            name='to_status',
            field=models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('POOL', 'Pool'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
    ]
