# Generated by Django 6.0.3 on 2026-04-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_alter_approvaltask_status_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('purchase', '0010_purchaserequestcontentaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='request_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='request_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='purchase.purchaserequest'),
        ),
    ]
