# Generated by Django 6.0.3 on 2026-04-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0008_backfill_generic_request_refs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='request_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Request'), ('TRAVEL', 'Travel Request'), ('PROJECT', 'Project')], max_length=20),
        ),
    ]
