# Generated by Django 6.0.3 on 2026-05-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0009_alter_approvalrule_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrulestep',
            name='sla_days',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
