# Generated by Django 6.0.3 on 2026-05-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0010_approvalrulestep_sla_days_approvaltask_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='escalation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='last_escalation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
