# Generated by Django 6.0.3 on 2026-05-05 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0011_approvaltask_escalation_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REMINDER', 'Reminder'), ('ESCALATION', 'Escalation')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body_preview', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DRY_RUN', 'Dry Run')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('triggered_by_command', models.CharField(blank=True, default='', max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='approvals.approvaltask')),
            ],
            options={
                'db_table': 'PS_A8_APR_NOTIFY_LOG',
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
