# Generated by Django 6.0.3 on 2026-05-12 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_departmentapprovalconfig'),
        ('approvals', '0014_approvaltask_generic_request_step_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltaskhistory',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACTIVATED', 'Activated'), ('CLAIMED', 'Claimed'), ('RELEASED_TO_POOL', 'Released to Pool'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('REASSIGNED', 'Reassigned'), ('DELEGATED', 'Delegated')], max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('request_type', models.CharField(blank=True, choices=[('PURCHASE', 'Purchase Request'), ('TRAVEL', 'Travel Request'), ('PROJECT', 'Project')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approval_delegations', to=settings.AUTH_USER_MODEL)),
                ('delegate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_delegations_to', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_delegations', to='accounts.department')),
                ('original_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_delegations_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Delegation',
                'verbose_name_plural': 'Approval Delegations',
                'db_table': 'PS_A8_AP_DELEG',
                'ordering': ['-start_date', 'original_approver'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalEscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, choices=[('PURCHASE', 'Purchase Request'), ('TRAVEL', 'Travel Request'), ('PROJECT', 'Project')], default='', max_length=20)),
                ('step_type', models.CharField(blank=True, choices=[('REQUESTER_MANAGER', 'Requester Manager'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('SPECIFIC_USER', 'Specific User'), ('DEPARTMENT_APPROVER', 'Department Approver'), ('FINANCE', 'Finance'), ('PURCHASING', 'Purchasing'), ('HR', 'HR'), ('GLOBAL_APPROVER', 'Global Approver')], default='', max_length=30)),
                ('overdue_days', models.PositiveIntegerField(default=2)),
                ('escalate_to_role', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('escalate_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_escalation_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Escalation Policy',
                'verbose_name_plural': 'Approval Escalation Policies',
                'db_table': 'PS_A8_AP_ESC_POL',
            },
        ),
    ]
