# Generated by Django 6.0.3 on 2026-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0015_alter_approvaltaskhistory_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='approval_rule_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='approval_rule_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='approval_rule_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='assigned_role',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='candidate_pool_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='snapshot_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='step_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
